/******
 *
 * @kdichon @copyright
 */
const next = require('./../../assets/images/next.png');
const cycle = require('./../../assets/images/cycle.png');
const yoga = require('./../../assets/images/yoga.png');
const walk = require('./../../assets/images/walk.png');
const star = require('./../../assets/images/Star.png');

export const products = [
  {
    id: 1,
    title: 'iPhone 9',
    description: 'An apple mobile which is nothing like apple',
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: 'Apple',
    category: 'smartphones',
    thumbnail: 'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/1/1.jpg',
      'https://i.dummyjson.com/data/products/1/2.jpg',
      'https://i.dummyjson.com/data/products/1/3.jpg',
      'https://i.dummyjson.com/data/products/1/4.jpg',
      'https://i.dummyjson.com/data/products/1/thumbnail.jpg',
    ],
  },
  {
    id: 2,
    title: 'iPhone X',
    description:
      'SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...',
    price: 899,
    discountPercentage: 17.94,
    rating: 4.44,
    stock: 34,
    brand: 'Apple',
    category: 'smartphones',
    thumbnail: 'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/2/1.jpg',
      'https://i.dummyjson.com/data/products/2/2.jpg',
      'https://i.dummyjson.com/data/products/2/3.jpg',
      'https://i.dummyjson.com/data/products/2/thumbnail.jpg',
    ],
  },
  {
    id: 3,
    title: 'Samsung Universe 9',
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    discountPercentage: 15.46,
    rating: 4.09,
    stock: 36,
    brand: 'Samsung',
    category: 'smartphones',
    thumbnail: 'https://i.dummyjson.com/data/products/3/thumbnail.jpg',
    images: ['https://i.dummyjson.com/data/products/3/1.jpg'],
  },
  {
    id: 4,
    title: 'OPPOF19',
    description: 'OPPO F19 is officially announced on April 2021.',
    price: 280,
    discountPercentage: 17.91,
    rating: 4.3,
    stock: 123,
    brand: 'OPPO',
    category: 'smartphones',
    thumbnail: 'https://i.dummyjson.com/data/products/4/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/4/1.jpg',
      'https://i.dummyjson.com/data/products/4/2.jpg',
      'https://i.dummyjson.com/data/products/4/3.jpg',
      'https://i.dummyjson.com/data/products/4/4.jpg',
      'https://i.dummyjson.com/data/products/4/thumbnail.jpg',
    ],
  },
  {
    id: 5,
    title: 'Huawei P30',
    description:
      'Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.',
    price: 499,
    discountPercentage: 10.58,
    rating: 4.09,
    stock: 32,
    brand: 'Huawei',
    category: 'smartphones',
    thumbnail: 'https://i.dummyjson.com/data/products/5/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/5/1.jpg',
      'https://i.dummyjson.com/data/products/5/2.jpg',
      'https://i.dummyjson.com/data/products/5/3.jpg',
    ],
  },
  {
    id: 6,
    title: 'MacBook Pro',
    description:
      'MacBook Pro 2021 with mini-LED display may launch between September, November',
    price: 1749,
    discountPercentage: 11.02,
    rating: 4.57,
    stock: 83,
    brand: 'Apple',
    category: 'laptops',
    thumbnail: 'https://i.dummyjson.com/data/products/6/thumbnail.png',
    images: [
      'https://i.dummyjson.com/data/products/6/1.png',
      'https://i.dummyjson.com/data/products/6/2.jpg',
      'https://i.dummyjson.com/data/products/6/3.png',
      'https://i.dummyjson.com/data/products/6/4.jpg',
    ],
  },
  {
    id: 7,
    title: 'Samsung Galaxy Book',
    description:
      'Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched',
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: 'Samsung',
    category: 'laptops',
    thumbnail: 'https://i.dummyjson.com/data/products/7/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/7/1.jpg',
      'https://i.dummyjson.com/data/products/7/2.jpg',
      'https://i.dummyjson.com/data/products/7/3.jpg',
      'https://i.dummyjson.com/data/products/7/thumbnail.jpg',
    ],
  },
  {
    id: 8,
    title: 'Microsoft Surface Laptop 4',
    description:
      'Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.',
    price: 1499,
    discountPercentage: 10.23,
    rating: 4.43,
    stock: 68,
    brand: 'Microsoft Surface',
    category: 'laptops',
    thumbnail: 'https://i.dummyjson.com/data/products/8/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/8/1.jpg',
      'https://i.dummyjson.com/data/products/8/2.jpg',
      'https://i.dummyjson.com/data/products/8/3.jpg',
      'https://i.dummyjson.com/data/products/8/4.jpg',
      'https://i.dummyjson.com/data/products/8/thumbnail.jpg',
    ],
  },
  {
    id: 9,
    title: 'Infinix INBOOK',
    description:
      'Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty',
    price: 1099,
    discountPercentage: 11.83,
    rating: 4.54,
    stock: 96,
    brand: 'Infinix',
    category: 'laptops',
    thumbnail: 'https://i.dummyjson.com/data/products/9/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/9/1.jpg',
      'https://i.dummyjson.com/data/products/9/2.png',
      'https://i.dummyjson.com/data/products/9/3.png',
      'https://i.dummyjson.com/data/products/9/4.jpg',
      'https://i.dummyjson.com/data/products/9/thumbnail.jpg',
    ],
  },
  {
    id: 10,
    title: 'HP Pavilion 15-DK1056WM',
    description:
      'HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10',
    price: 1099,
    discountPercentage: 6.18,
    rating: 4.43,
    stock: 89,
    brand: 'HP Pavilion',
    category: 'laptops',
    thumbnail: 'https://i.dummyjson.com/data/products/10/thumbnail.jpeg',
    images: [
      'https://i.dummyjson.com/data/products/10/1.jpg',
      'https://i.dummyjson.com/data/products/10/2.jpg',
      'https://i.dummyjson.com/data/products/10/3.jpg',
      'https://i.dummyjson.com/data/products/10/thumbnail.jpeg',
    ],
  },
];

export const popular = [
  {
    id: 51,
    title: 'half sleeves T shirts',
    description:
      'Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands',
    price: 23,
    discountPercentage: 12.76,
    rating: 4.26,
    stock: 132,
    brand: 'Vintage Apparel',
    category: 'mens-shirts',
    thumbnail: 'https://i.dummyjson.com/data/products/51/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/51/1.png',
      'https://i.dummyjson.com/data/products/51/2.jpg',
      'https://i.dummyjson.com/data/products/51/3.jpg',
      'https://i.dummyjson.com/data/products/51/thumbnail.jpg',
    ],
  },
  {
    id: 52,
    title: 'FREE FIRE T Shirt',
    description:
      "quality and professional print - It doesn't just look high quality, it is high quality.",
    price: 10,
    discountPercentage: 14.72,
    rating: 4.52,
    stock: 128,
    brand: 'FREE FIRE',
    category: 'mens-shirts',
    thumbnail: 'https://i.dummyjson.com/data/products/52/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/52/1.png',
      'https://i.dummyjson.com/data/products/52/2.png',
      'https://i.dummyjson.com/data/products/52/3.jpg',
      'https://i.dummyjson.com/data/products/52/4.jpg',
      'https://i.dummyjson.com/data/products/52/thumbnail.jpg',
    ],
  },
  {
    id: 53,
    title: 'printed high quality T shirts',
    description: 'Brand: vintage Apparel ,Export quality',
    price: 35,
    discountPercentage: 7.54,
    rating: 4.89,
    stock: 6,
    brand: 'Vintage Apparel',
    category: 'mens-shirts',
    thumbnail: 'https://i.dummyjson.com/data/products/53/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/53/1.webp',
      'https://i.dummyjson.com/data/products/53/2.jpg',
      'https://i.dummyjson.com/data/products/53/3.jpg',
      'https://i.dummyjson.com/data/products/53/4.jpg',
      'https://i.dummyjson.com/data/products/53/thumbnail.jpg',
    ],
  },
  {
    id: 54,
    title: 'Pubg Printed Graphic T-Shirt',
    description:
      'Product Description Features: 100% Ultra soft Polyester Jersey. Vibrant & colorful printing on front. Feels soft as cotton without ever cracking',
    price: 46,
    discountPercentage: 16.44,
    rating: 4.62,
    stock: 136,
    brand: 'The Warehouse',
    category: 'mens-shirts',
    thumbnail: 'https://i.dummyjson.com/data/products/54/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/54/1.jpg',
      'https://i.dummyjson.com/data/products/54/2.jpg',
      'https://i.dummyjson.com/data/products/54/3.jpg',
      'https://i.dummyjson.com/data/products/54/4.jpg',
      'https://i.dummyjson.com/data/products/54/thumbnail.jpg',
    ],
  },
  {
    id: 55,
    title: 'Money Heist Printed Summer T Shirts',
    description: 'Fabric Jercy, Size: M & L Wear Stylish Dual Stiched',
    price: 66,
    discountPercentage: 15.97,
    rating: 4.9,
    stock: 122,
    brand: 'The Warehouse',
    category: 'mens-shirts',
    thumbnail: 'https://i.dummyjson.com/data/products/55/thumbnail.jpg',
    images: [
      'https://i.dummyjson.com/data/products/55/1.jpg',
      'https://i.dummyjson.com/data/products/55/2.webp',
      'https://i.dummyjson.com/data/products/55/3.jpg',
      'https://i.dummyjson.com/data/products/55/4.jpg',
      'https://i.dummyjson.com/data/products/55/thumbnail.jpg',
    ],
  },
];

export const categories = [
  {id: 1, name: 'All'},
  {id: 2, name: 'Laptops'},
  {id: 3, name: 'Fragrances'},
  {id: 4, name: 'Skincare'},
  {id: 5, name: 'Groceries'},
  {id: 6, name: 'Home decoration'},
  {id: 7, name: 'Furniture'},
  {id: 0, name: 'Tops'},
];

export const singleProduct = {
  id: 10,
  title: 'HP Pavilion 15-DK1056WM',
  description:
    'HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10',
  price: 1099,
  discountPercentage: 6.18,
  rating: 4.43,
  stock: 89,
  brand: 'HP Pavilion',
  category: 'laptops',
  thumbnail: 'https://i.dummyjson.com/data/products/10/thumbnail.jpeg',
  images: [
    'https://i.dummyjson.com/data/products/10/1.jpg',
    'https://i.dummyjson.com/data/products/10/2.jpg',
    'https://i.dummyjson.com/data/products/10/3.jpg',
    'https://i.dummyjson.com/data/products/10/thumbnail.jpeg',
  ],
};

export const data = [
  {
    id: 1,
    name: 'Elastique',
    status: 85,
    image: cycle,
    lightColor: '#f8e4d9',
    color: '#fcf1ea',
    darkColor: '#fac5a4',
  },
  {
    id: 2,
    name: 'Running',
    status: 25,
    image: walk,
    lightColor: '#d7f0f7',
    color: '#e8f7fc',
    darkColor: '#aceafc',
  },
  {
    id: 3,
    name: 'Weight',
    status: 85,
    image: yoga,
    lightColor: '#dad5fe',
    color: '#e7e3ff',
    darkColor: '#8860a2',
  },
];
